### ISSUE TITLE
bin/console system:setup error

### ISSUE THREAD

**Issue by kashifmian722** [shopwareDowntown/downtown#368]
Im facing this error when i try to run this command while setting up downtown on linux.

dev@2844bf22092d /var/www/html $ bin/console system:setup

Fatal error: Uncaught OutOfBoundsException: Package "shopware/platform" is not installed in /var/www/html/vendor/composer/InstalledVersions.php:201
Stack trace:
#0 /var/www/html/vendor/composer/package-versions-deprecated/src/PackageVersions/Versions.php(68): Composer\InstalledVersions::getPrettyVersion('shopware/platfo...')
#1 /var/www/html/vendor/shopware/core/HttpKernel.php(182): PackageVersions\Versions::getVersion('shopware/platfo...')
#2 /var/www/html/vendor/shopware/core/HttpKernel.php(92): Shopware\Core\HttpKernel->createKernel()
#3 /var/www/html/bin/console(67): Shopware\Core\HttpKernel->getKernel()
#4 {main}
  thrown in /var/www/html/vendor/composer/InstalledVersions.php on line 201

**Comment by ManuelK2000** [comment]
I can confirm this issue.
We are facing the same problem during installation.
Currently looking for an solution...

**Comment by kashifmian722** [comment]
Dear any update on this issue. or can I use other shopware platform installation with this bundle?
